### ISSUE TITLE
Difficulty distinguishing between folders and files in the printed tree

### ISSUE THREAD

**Issue by hahv** [santisq/PSTree#27]
In the printed tree structure, specifically when a folder contains no subfolders or files, it becomes challenging to distinguish between a folder and a file. An effective solution is to visually differentiate folders by providing them with a distinct background, as demonstrated in the tree command output in Ubuntu, as shown in the image below (for _mk_dataset folder)

![image](https://github.com/santisq/PSTree/assets/8085290/8be4be27-30a2-413f-8feb-bb82f7b8a175)

**Comment by santisq** [comment]
Hi @hahv, this is what the [`Mode` property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.filesystemprovider.mode?view=powershellsdk-7.4.0#microsoft-powershell-commands-filesystemprovider-mode(system-management-automation-psobject)) is for, it represents a flag in the [`FileAttributes` enum](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=net-8.0), i.e.: `a` is for `Archive`, `d` is for `Directory`, `h` is for `Hidden`, `r` is for `ReadOnly` and so on.

**Comment by hahv** [comment]
@santisq oh I see, thank you. 

I suppose my suggestion could be a feature improvement

I'll close this issue.

**Comment by santisq** [comment]
@hahv I actually had this idea in the past, i.e. adding emojis for files and folders but I wasn't sure if I should cause that would be breaking folks using older terminals. But I like the idea about coloring, might do something like that in the future. Tho, the other problem is that pwsh 7+ console background is black by default whereas pwsh 5.1 is blue so that is also something to consider, not all colors look good in blue background consoles. I'm open to suggestions!

**Comment by hahv** [comment]
That's great. I look forward to seeing it in action. Thank you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by santisq** [comment]
Hi @hahv, I remember you mentioned having colored output. Do you like how this looks? It's using the same colors as `Get-ChildItem` (I'm not convinced on how it looks 🤣)

![image](https://github.com/user-attachments/assets/114e5bd7-acdb-478d-a214-3c614622299d)

**Comment by hahv** [comment]
@santisq it seems ok for me. At least, I can got a quick glance and know what to find (folders or files)

**Comment by santisq** [comment]
Hey @hahv, [v2.2.0](https://github.com/santisq/PSTree/releases/tag/v2.2.0) will be published in a few minutes. Hope you like it :)

**Comment by hahv** [comment]
@santisq great. Thank you for your effort.
