### ISSUE TITLE
Name / Size columns can have large separation in default output

### ISSUE THREAD

**Issue by roysubs** [santisq/PSTree#7]
I feel that in output with a lot of depth, the Size column can be very far from the name of the object, making it hard to line up, e.g. outputs like this.
![image](https://user-images.githubusercontent.com/16388699/201686075-f535aab2-956e-4ee5-8d67-285953d18dce.png)
At first, I thought that putting Size to the left of the object names might make it more readable, but the hierarchy characters might not make that ideal. Possibly best of all might be an option that gives a `   -   -   -   ` (with 3 spaces between each '-' would give good visibility on every other line) making it much easier to correlate Name and Size. 
![image](https://user-images.githubusercontent.com/16388699/201686939-dc5ab60b-437e-43d6-b3a3-c5ee341168a8.png)

**Comment by santisq** [comment]
@roysubs piping the output to `Format-Table -AutoSize` would sort this problem out. Format types don't have a good auto size mechanism, either a fixed size for all columns or let it decide what's the best size for each column (which, not always is the greatest). As for having the `Size` column in the left-side of `Hierarchy`, I don't like the way it looks but you can use `Select-Object` or fork the repo and update the format file: https://github.com/santisq/PSTree/blob/main/PSTree.Format.ps1xml to make it look the way you want.

**Comment by santisq** [comment]
Due to the format type limitation described before this will not be fixed for now.

**Comment by roysubs** [comment]
How do you do a select for these exactly? Best I could achieve was `pstree | select Length,Mode,Hierarchy`. Is there a way to retain the human readable format on the Length/Size column in doing this? What should Mode be to get the attributes (`attributes` also doesn't work)? I also note that this works `(pstree).Hierarchy`, but `(pstree).Length` seems to give a count of the number of objects.

**Comment by santisq** [comment]
@roysubs hope this new update makes it easy to export output. I have added the most used attributes files and directories.
