### ISSUE TITLE
Sort by ascending values

### ISSUE THREAD

**Issue by jlnrrg** [santisq/PSTree#9]
I noticed that the default output is sorted descending.
It has been a long time since I last worked with PS, so I am not aware how to resort the tree later on.
If you know I would be happy for advice, otherwise I would propose a sorting flag, or to make the default sort ascending, as that would mimik the default windows explorer sorting behaviour.

Cmd I've run: `Get-PSTree -Directory`

**Comment by krzydoug** [comment]
Now that you've rewritten in C#, shouldn't it be easy to sort it ascending by default now? I'm guessing here but wondered if you thought about it. The link to the stack<T> code is broken now by the way.
